version: '1'
services:
  client:
    depends_on: [server]
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
    restart: on-failure
    container_name: client

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes: 
      - /app/node_modules
    restart: on-failure
    container_name: server
    env_file:
      - ./server/.env

  mongo:
    image: mongo
    restart: on-failure
    container_name: mongo
    volumes:
      - ./db/mongo:/data/db
